[tox]
envlist=py{39,310,311,312,313}-marshmallow{3,4}

[testenv]
deps=
    -r requirements-test.txt
    marshmallow3: marshmallow>=3.13,<4
    marshmallow4: marshmallow>=4,<5
allowlist_externals=make
commands=make test_coverage
